export const ACTIVITY_LIST_REQUEST = 'ACTIVITY_LIST_REQUEST'
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS'
export const ACTIVITY_LIST_FAIL = 'ACTIVITY_LIST_FAIL'

export const ACTIVITY_DETAILS_REQUEST = 'ACTIVITY_DETAILS_REQUEST'
export const ACTIVITY_DETAILS_SUCCESS = 'ACTIVITY_DETAILS_SUCCESS'
export const ACTIVITY_DETAILS_FAIL = 'ACTIVITY_DETAILS_FAIL'

export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST'
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS'
export const ACTIVITY_DELETE_FAIL = 'ACTIVITY_DELETE_FAIL'

export const ACTIVITY_CREATE_REQUEST = 'ACTIVITY_CREATE_REQUEST'
export const ACTIVITY_CREATE_SUCCESS = 'ACTIVITY_CREATE_SUCCESS'
export const ACTIVITY_CREATE_FAIL = 'ACTIVITY_CREATE_FAIL'
export const ACTIVITY_CREATE_RESET = 'ACTIVITY_CREATE_RESET'

export const ACTIVITY_UPDATE_REQUEST = 'ACTIVITY_UPDATE_REQUEST'
export const ACTIVITY_UPDATE_SUCCESS = 'ACTIVITY_UPDATE_SUCCESS'
export const ACTIVITY_UPDATE_FAIL = 'ACTIVITY_UPDATE_FAIL'
export const ACTIVITY_UPDATE_RESET = 'ACTIVITY_UPDATE_RESET'

export const ACTIVITY_CREATE_REVIEW_REQUEST = 'ACTIVITY_CREATE_REVIEW_REQUEST'
export const ACTIVITY_CREATE_REVIEW_SUCCESS = 'ACTIVITY_CREATE_REVIEW_SUCCESS'
export const ACTIVITY_CREATE_REVIEW_FAIL = 'ACTIVITY_CREATE_REVIEW_FAIL'
export const ACTIVITY_CREATE_REVIEW_RESET = 'ACTIVITY_CREATE_REVIEW_RESET'

export const ACTIVITY_TOP_REQUEST = 'ACTIVITY_TOP_REQUEST'
export const ACTIVITY_TOP_SUCCESS = 'ACTIVITY_TOP_SUCCESS'
export const ACTIVITY_TOP_FAIL = 'ACTIVITY_TOP_FAIL'


export const ACTIVITY_LIST_MY_FAIL = 'ACTIVITY_LIST_MY_FAIL'
export const ACTIVITY_LIST_MY_REQUEST = 'ACTIVITY_LIST_MY_REQUEST' 
export const ACTIVITY_LIST_MY_SUCCESS = 'ACTIVITY_LIST_MY_SUCCESS'
export const ACTIVITY_LIST_MY_RESET = 'ACTIVITY_LIST_MY_RESET'
